<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getISMemDataImplAsDoc</value>
  <value name="encodeutf8">true</value>
  <value name="body">ICBJRGF0YUN1cnNvciBwYyA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KICB0cnl7DQoJICBJU01l
bURhdGFJbXBsIGltZGkgID0gKElTTWVtRGF0YUltcGwpSURhdGFVdGlsLmdldChwYywgImlzTWVt
RGF0YUltcGwiKTsNCgkgIElEYXRhSlNPTkNvZGVyIGlkYyA9IG5ldyBJRGF0YUpTT05Db2Rlcigp
Ow0KCSAgYnl0ZVtdIGJ5dGVzID0gaWRjLmVuY29kZVRvQnl0ZXMoaW1kaSk7DQoJICBJRGF0YSBk
b2MgPSBpZGMuZGVjb2RlRnJvbUJ5dGVzKGJ5dGVzKTsNCgkgIElEYXRhVXRpbC5wdXQocGMsICJk
b2MiLCBkb2MpOw0KICB9Y2F0Y2ggKEV4Y2VwdGlvbiBlKXsNCgkgIHRocm93IG5ldyBTZXJ2aWNl
RXhjZXB0aW9uKGUpOw0KICB9IGZpbmFsbHkgew0KCSAgcGMuZGVzdHJveSgpOw0KICB9</value>
</Values>
